"""Phase 4: Chat session updated_at

Revision ID: 01408d4785c2
Revises: 6c8634f69762
Create Date: 2026-04-26 13:51:03.090976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01408d4785c2'
down_revision: Union[str, Sequence[str], None] = '6c8634f69762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'updated_at')
    # ### end Alembic commands ###
